### ISSUE TITLE
Project has no license in source tree

### ISSUE THREAD

**Issue by ErikWiklund** [coryb/slipscheme#2]
I would appreciate if a license file was added so that it is obvious which software license applies.

**Comment by ErikWiklund** [comment]
Again, please add a license or is this intentionally not licensed?
https://choosealicense.com/no-permission/
https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users

**Comment by coryb** [comment]
Sorry, have not looked at this project in a long while, added APLv2 license.

**Comment by ErikWiklund** [comment]
Thank you for finally resolving this issue; unfortunately my project ended up being scrapped due to other technical issues, not this thankfully.
